### ISSUE TITLE
Bump dependency versions

### ISSUE THREAD

**Issue by ryzokuken** [osdc/osdc.github.io#42]
We have a couple dependencies with security vulnerabilities. It would be a great idea to update them all to the newest versions.

/cc @saranshbarua @codekhal

**Comment by Yugandhartripathi** [comment]
yarn audit and outdated show severe vulnerabilities with currently used gatsby version but simply <br>`yarn upgrade --latest`<br> will break the code because of huge changes in Gatsby from V1 to V2. 
So what's our move here @ryzokuken @saranshbarua full migration to V2? <br>If yes then it needs a lots of changes listed here : https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/ .

**Comment by ryzokuken** [comment]
@Yugandhartripathi full migration seems inevitable. Are you up for it?

**Comment by Yugandhartripathi** [comment]
@ryzokuken I am on it :+1:

**Comment by Yugandhartripathi** [comment]
@ryzokuken @saranshbarua I am stuck. Need help resolving below warning <br>
![image](https://user-images.githubusercontent.com/32102845/51492308-69b2a400-1dd7-11e9-9db3-3b8d5bd923c7.png)
https://github.com/yannickcr/eslint-plugin-react#configuration - link in terminal<br>
We don't have eslint in our project explicitly configured with .eslintrc.json or package.json but we do get it automatically in yarn.lock as visible in below img and here we have react version defined clearly.
![image](https://user-images.githubusercontent.com/32102845/51492411-bbf3c500-1dd7-11e9-8cf3-54fbe3315012.png)

**Comment by Yugandhartripathi** [comment]
@ryzokuken  @saranshbarua please review.
